import { useState } from 'react';
import FormulaCard from '../shared/FormulaCard';

interface Concept {
  id: string;
  title: string;
  category: string;
  formula?: string;
  description: string;
  deepDive: string;
  variables?: { symbol: string; meaning: string }[];
}

const concepts: Concept[] = [
  {
    id: 'downforce', title: 'Downforce', category: 'Aerodynamics',
    formula: 'F = ½ × ρ × v² × Cl × A',
    description: 'The force that pushes the car onto the track, generated by the car\'s wings and body shape.',
    deepDive: 'Downforce is essentially inverted lift — like an airplane wing flipped upside down. It increases with the square of speed (v²), which means doubling your speed gives 4× the downforce. At 300 kph, an F1 car generates enough downforce to theoretically drive upside down on a ceiling! The trade-off is that the same wing shape also creates drag, which slows you down on straights.',
    variables: [
      { symbol: 'ρ', meaning: 'Air density (1.225 kg/m³ at sea level)' },
      { symbol: 'v', meaning: 'Speed in m/s' },
      { symbol: 'Cl', meaning: 'Lift coefficient (depends on wing shape/angle)' },
      { symbol: 'A', meaning: 'Reference area (frontal area of the car)' },
    ],
  },
  {
    id: 'drag', title: 'Drag Force', category: 'Aerodynamics',
    formula: 'F = ½ × ρ × v² × Cd × A',
    description: 'Air resistance that opposes the car\'s motion. Same v² relationship as downforce.',
    deepDive: 'Drag is the enemy of straight-line speed. Since it grows with v², going from 300 to 350 kph requires enormously more power than going from 200 to 250 kph. This is why reducing Cd (drag coefficient) by even 0.01 is a huge deal in F1. Teams spend millions on wind tunnels and CFD (computational fluid dynamics) to shave tiny fractions off Cd.',
  },
  {
    id: 'ld-ratio', title: 'L/D Ratio (Aero Efficiency)', category: 'Aerodynamics',
    formula: 'L/D = Cl / Cd',
    description: 'The holy grail metric — how much downforce you get for each unit of drag.',
    deepDive: 'A higher L/D ratio means you can go faster in corners (more downforce) without losing as much speed on straights (less drag). F1 cars achieve L/D ratios of 3-5, while commercial aircraft aim for 15-20. The difference is that F1 cars operate very close to the ground and need massive downforce, which inevitably creates more drag.',
  },
  {
    id: 'corner-speed', title: 'Maximum Cornering Speed', category: 'Tire Physics',
    formula: 'v = √(μ × g × r)',
    description: 'The fastest you can take a corner without sliding off — depends on grip and corner radius.',
    deepDive: 'This formula comes from balancing centripetal force (what keeps you turning) with friction force (what your tires provide). The friction coefficient μ for F1 tires is about 1.8 — much higher than road tires (~1.0). Downforce increases the normal force on tires, which means more grip, which means higher corner speeds. This is why aero is so important — it literally lets you corner faster.',
    variables: [
      { symbol: 'μ', meaning: 'Friction coefficient (tire grip)' },
      { symbol: 'g', meaning: 'Gravity (9.81 m/s²)' },
      { symbol: 'r', meaning: 'Corner radius in meters' },
    ],
  },
  {
    id: 'grip-circle', title: 'Traction Circle', category: 'Tire Physics',
    formula: '√(F_long² + F_lat²) ≤ F_max',
    description: 'A tire has a maximum total grip. You can use it for braking, cornering, or a mix — but not both at maximum.',
    deepDive: 'Imagine the grip as a circle. Pure braking uses the top of the circle. Pure cornering uses the sides. The fastest drivers "trace the edge" of the circle — they combine braking and turning to use 100% of available grip at all times. This is called "trail braking" — gradually releasing the brake as you add steering input. If you exceed the circle (brake too hard while turning), the tire slides.',
  },
  {
    id: 'weight-transfer', title: 'Weight Transfer', category: 'Vehicle Dynamics',
    formula: 'ΔW = m × a × h / L',
    description: 'Under braking, weight shifts to the front wheels. Under acceleration, it shifts to the rear.',
    deepDive: 'Weight transfer is why the front of an F1 car dips under braking. It\'s not the springs compressing (though that happens too) — it\'s actual load transfer from rear to front axle. This means front tires have MORE grip and rear tires have LESS grip under braking. Brake balance (how much braking force goes to front vs rear) must account for this, or the car will lock up or spin.',
    variables: [
      { symbol: 'm', meaning: 'Car mass' },
      { symbol: 'a', meaning: 'Deceleration (m/s²)' },
      { symbol: 'h', meaning: 'Center of gravity height' },
      { symbol: 'L', meaning: 'Wheelbase (distance between axles)' },
    ],
  },
  {
    id: 'power-torque', title: 'Power vs Torque', category: 'Powertrain',
    formula: 'P = T × RPM × 2π / 60',
    description: 'Torque is the twisting force. Power is torque times how fast it\'s applied.',
    deepDive: 'Think of torque like how hard you push a wrench, and power as how fast you spin it. A diesel truck has massive torque (great at low RPM) but moderate power. An F1 engine has less torque but spins at 15,000 RPM, giving enormous power. Power determines top speed and acceleration. Torque determines how "punchy" the engine feels. F1 engines produce about 350 Nm of torque but 750+ kW of power.',
  },
  {
    id: 'ers', title: 'Energy Recovery System', category: 'Powertrain',
    formula: 'E = ½ × m × v²',
    description: 'F1 cars harvest kinetic energy during braking and deploy it as extra power on straights.',
    deepDive: 'When you brake, kinetic energy (½mv²) normally turns into heat in the brake discs. The MGU-K (Motor Generator Unit - Kinetic) captures some of this energy and stores it in a battery. On the next straight, it deploys up to 120kW of extra power. The MGU-H does the same with waste heat from the turbocharger exhaust. Together, they make F1 power units about 50% thermally efficient — the most efficient ICEs ever built.',
  },
  {
    id: 'tire-deg', title: 'Tire Degradation', category: 'Strategy',
    formula: 'Δt = base_deg × lap^1.3',
    description: 'Tires lose grip over time, making lap times progressively slower.',
    deepDive: 'Tire degradation is non-linear — it gets worse and worse the longer you stay out. Soft tires are 1-2 seconds faster than hards initially, but degrade 3-4× faster. Strategy engineers must balance: do you start fast on softs and pit early, or start on hards and pit later? The "crossover point" — where a degraded soft equals a fresh hard — is the key number that determines optimal strategy.',
  },
  {
    id: 'pit-window', title: 'Pit Stop Window', category: 'Strategy',
    description: 'The optimal lap to make a pit stop, balancing tire degradation against pit stop time loss.',
    deepDive: 'A pit stop costs about 22-25 seconds (driving through the pit lane + tire change). To justify stopping, the time saved from fresh tires must exceed this cost. If your tires are losing 0.5s per lap, you need to pit before you\'ve lost 25s cumulative. But it\'s more complex: the undercut (pitting before your rival) gives you fresh tire advantage for a few laps, which can be enough to gain track position.',
  },
];

const categories = [...new Set(concepts.map(c => c.category))];

export default function Learn() {
  const [activeCategory, setActiveCategory] = useState<string>(categories[0]);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const filtered = concepts.filter(c => c.category === activeCategory);

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <h2 className="text-2xl font-black text-white mb-2">📚 Learn</h2>
      <p className="text-slate-400 text-sm mb-6">Real motorsport engineering concepts explained. These are the same formulas and principles used by real F1 engineers.</p>

      {/* Category tabs */}
      <div className="flex gap-2 mb-6 flex-wrap">
        {categories.map(cat => (
          <button
            key={cat}
            onClick={() => setActiveCategory(cat)}
            className={`px-4 py-2 rounded-lg text-sm font-semibold transition-colors ${
              activeCategory === cat
                ? 'bg-xp-bar text-white'
                : 'bg-racing-panel text-slate-400 hover:text-white border border-racing-border'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Concept Cards */}
      <div className="space-y-4">
        {filtered.map(concept => (
          <div key={concept.id} className="bg-racing-panel border border-racing-border rounded-xl overflow-hidden">
            <button
              onClick={() => setExpandedId(expandedId === concept.id ? null : concept.id)}
              className="w-full p-4 text-left hover:bg-slate-800/50 transition-colors"
            >
              <div className="flex items-center justify-between">
                <h4 className="text-white font-bold">{concept.title}</h4>
                <span className="text-slate-500 text-sm">{expandedId === concept.id ? '▼' : '▶'}</span>
              </div>
              <p className="text-slate-400 text-sm mt-1">{concept.description}</p>
            </button>

            {expandedId === concept.id && (
              <div className="px-4 pb-4 slide-in">
                {concept.formula && (
                  <FormulaCard
                    title={concept.title}
                    formula={concept.formula}
                    description=""
                    variables={concept.variables}
                  />
                )}
                <div className="bg-slate-900 rounded-lg p-4 text-sm text-slate-300 leading-relaxed">
                  {concept.deepDive}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
